# Numpy

In [1]:
# import library
import numpy as np 

## 1. Create Array

### np.array()

In [4]:
list_angka = [1,2,3,4]
list_angka 

[1, 2, 3, 4]

In [5]:
# mengubah list menjadi array
np.array(list_angka)

array([1, 2, 3, 4])

In [12]:
array_of_list_angka = np.array(list_angka)

In [13]:
type(array_of_list_angka)

numpy.ndarray

In [6]:
list_b = [[1,2,3], [10,20,30], [100,200,300]]
list_b

[[1, 2, 3], [10, 20, 30], [100, 200, 300]]

In [7]:
np.array(list_b) 

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [9]:
list_b = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
]

In [10]:
np.array(list_b)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### np.arange()

In [201]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [202]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [14]:
np.arange(1,6,2) 

array([1, 3, 5])

In [15]:
np.arange(start=1, stop=6, step=2)

array([1, 3, 5])

In [16]:
np.arange(stop=6, step=2, start=1) 

array([1, 3, 5])

### np.zeros()

In [206]:
# membuat array berisi angka 0 semua
np.zeros(5) 

array([0., 0., 0., 0., 0.])

In [207]:
np.zeros((2,4)) 
# array 2 dimensi: 2 baris dan 4 kolom

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones()

In [17]:
# membuat array berisi angka 1 semua
np.ones(5) 

array([1., 1., 1., 1., 1.])

In [18]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### np.eye()

In [209]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.linspace()

In [19]:
# membuat array yang membagi sekian elemen dengan interval yang sama
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [214]:
np.linspace(0,99,5)

array([ 0.  , 24.75, 49.5 , 74.25, 99.  ])

In [20]:
np.linspace(start=0, stop=100, num=5) 

array([  0.,  25.,  50.,  75., 100.])

**Soal**

Buat array dengan output [10,30,50,70]

In [216]:
np.arange(10,71,20)

array([10, 30, 50, 70])

In [217]:
np.linspace(10, 70, 4)

array([10., 30., 50., 70.])

In [218]:
np.array([10,30,50,70]) 

array([10, 30, 50, 70])

### np.random.rand()

In [2]:
# membuat array berisi angka random antara 0-1
np.random.rand(2)

array([0.79131203, 0.65104604])

In [3]:
np.random.rand(5,5)

array([[0.40275012, 0.26120448, 0.36520801, 0.9613777 , 0.6907866 ],
       [0.59360115, 0.33852102, 0.64333329, 0.34489899, 0.90065413],
       [0.56514434, 0.36473532, 0.61077024, 0.58550714, 0.3057189 ],
       [0.19730593, 0.71357079, 0.62049523, 0.90428603, 0.7313286 ],
       [0.17762913, 0.17653207, 0.54100456, 0.52491693, 0.65179814]])

In [221]:
# membuat array berisi angka yg terdistribusi normal dengan mean=0 dan std=1
np.random.seed(99)

np.random.randn(10)

array([-0.14235884,  2.05722174,  0.28326194,  1.32981198, -0.15462185,
       -0.06903086,  0.75518049,  0.82564665, -0.11306921, -2.36783759])

### np.random.randn()

In [4]:
np.random.randn(2)

array([-0.6475848 ,  1.13803217])

In [5]:
np.random.randn(5, 5)

array([[-0.11582285, -1.39594378, -0.15228623, -0.16834926,  0.00639121],
       [ 0.71451382,  0.94242498, -0.95451562, -2.02251221, -0.19837753],
       [-0.82249339,  0.11827727,  0.3319392 ,  1.4292196 , -0.39536493],
       [ 1.24231932,  0.6332214 ,  1.98073498,  0.6194244 ,  0.75581451],
       [ 2.22621586, -1.73708497,  0.19934215, -0.99275462, -0.36736871]])

### np.random.randint()

In [10]:
np.random.randint(1, 100)

16

In [11]:
np.random.randint(1, 100, 10)

array([10, 28, 32, 19,  1, 62, 43, 12, 18, 15])

In [12]:
np.random.randint(low=10, high=50, size=10)

array([19, 43, 18, 30, 18, 17, 39, 31, 35, 14])

In [13]:
np.random.randint(10, 50, 5)

array([35, 47, 37, 36, 44])

In [14]:
np.random.randint(low=10, high=12, size=15)

array([11, 11, 11, 10, 10, 11, 10, 11, 11, 10, 10, 10, 10, 10, 11])

## 2. Attributes and Methods

### shape

In [15]:
array1 = np.random.randint(0,100,10)
array1 

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [16]:
array1.shape
# mengetahui bentuk dari array

(10,)

In [17]:
array2 = np.array([[44, 47, 64], [67, 67,  9], [83, 21, 36]])
array2 
# array 2 dimensi

array([[44, 47, 64],
       [67, 67,  9],
       [83, 21, 36]])

In [18]:
array2.shape # array 2 dimensi: 3 baris dan 3 kolom

(3, 3)

In [19]:
array3 = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [20]:
array3.shape

(3, 3, 3)

### reshape()

In [21]:
array1

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [22]:
array1.shape # awalnya 1 dimensi

(10,)

In [23]:
# mengubah array 1 dimensi menjadi 2 dimensi
array1.reshape(5,2)

# reshape harus ke jumlah item yg sama

array([[69, 24],
       [ 6, 67],
       [ 1, 94],
       [26, 55],
       [37, 69]])

In [24]:
array1.reshape(1,10)
# ini array 2 dimensi: 1 baris

array([[69, 24,  6, 67,  1, 94, 26, 55, 37, 69]])

In [25]:
array1.reshape(3,3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [26]:
array3 = array1.reshape(2,5)
array3

array([[69, 24,  6, 67,  1],
       [94, 26, 55, 37, 69]])

In [27]:
# mengubah array 2 dimensi menjadi 1 dimensi
array3.reshape(10)

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [28]:
# mengubah array 2 dimensi menjadi 1 dimensi tanpa perlu mengetahui jumlah item
array3.reshape(-1) 

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

### max() min() argmax() argmin()

In [33]:
# maximum
array3.max()

np.int64(94)

In [34]:
# index dari nilai maximum
array3.argmax() 

np.int64(5)

In [35]:
# minimum
array3.min()

np.int64(1)

In [36]:
# index dari nilai minimum
array3.argmin() 

np.int64(4)

## 3. Indexing & Slicing 

### Indexing and Slicing 1D Array

In [37]:
array1 

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [38]:
# indexing 1 item
array1[2]

np.int64(6)

In [39]:
# slicing beberapa item
array1[7:]

array([55, 37, 69])

In [42]:
array1[-1]

np.int64(69)

In [40]:
array1[-3:]

array([55, 37, 69])

In [41]:
# array[start:stop:step]
array1[ : :-1] 

# semua item, dengan step mundur

array([69, 37, 55, 26, 94,  1, 67,  6, 24, 69])

In [43]:
# dari item index 1, sampai akhir, dengan step 2
array1[1: :2]

array([24, 67, 94, 55, 69])

In [44]:
array1

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [45]:
array1[2: :-1] 

array([ 6, 24, 69])

### Update Value

In [46]:
array1

array([69, 24,  6, 67,  1, 94, 26, 55, 37, 69])

In [47]:
# mengubah 3 item pertama menjadi 100
array1[0:3] = 100

In [48]:
array1

array([100, 100, 100,  67,   1,  94,  26,  55,  37,  69])

In [49]:
# mengubah 3 item pertama menjadi 1,2,3
array1[0:3] = [1,2,3]
array1 

array([ 1,  2,  3, 67,  1, 94, 26, 55, 37, 69])

In [50]:
array1[0] = 1000
array1

array([1000,    2,    3,   67,    1,   94,   26,   55,   37,   69])

hati-hati ketika mengubah isi array

In [53]:
array4 = np.arange(0,11,1)
array4 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [54]:
slice_of_array4 = array4[0:3]
slice_of_array4  

array([0, 1, 2])

In [55]:
# mengubah semua item dalam slice_of_array4 menjadi 88
slice_of_array4[:] = 88
slice_of_array4 

array([88, 88, 88])

In [56]:
array4 # item dalam array4 ikut berubah 

array([88, 88, 88,  3,  4,  5,  6,  7,  8,  9, 10])

Cara yang benar pakai copy()

In [57]:
array4 = np.arange(0,11,1)
array4 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [58]:
slice_of_array4 = array4[0:3].copy() 
slice_of_array4  

array([0, 1, 2])

In [59]:
slice_of_array4[:] = 88
slice_of_array4 

array([88, 88, 88])

In [60]:
array4 # aman, item dalam array4 tidak ikut berubah

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Slicing in 2D Array (matrix)

array[row, column]

In [61]:
array_2d = np.array([[10,15,20], [25,30,35], [40,45,50]])
array_2d 

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [62]:
# indexing baris index 0
array_2d[0] 

array([10, 15, 20])

In [63]:
array_2d[0][1:] 

array([15, 20])

In [64]:
# indexing baris index 2, kolom index 2
array_2d[2][2]

np.int64(50)

In [65]:
# indexing baris index 2, kolom index 2
array_2d[2, 2] 

np.int64(50)

In [66]:
array_2d[2, -1]  

np.int64(50)

In [67]:
array_2d 

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [68]:
# indexing kolom paling kiri (index 0)
array_2d[: , 0]

array([10, 25, 40])

In [69]:
array_2d[1: , 1:] 

array([[30, 35],
       [45, 50]])

In [70]:
array_2d[1:3, 0:2]

array([[25, 30],
       [40, 45]])

### Fancy Indexing

In [71]:
array5 = np.arange(0,100,10)
array5

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [72]:
# cara indexing pada index yg tidak berurut
# array[[index_b, index_c, index_a]]

array5[[7,3,4]] 

array([70, 30, 40])

In [73]:
array_2d 

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [74]:
# ambil baris paling atas dan paling bawah
array_2d[[0, 2]]

array([[10, 15, 20],
       [40, 45, 50]])

### Conditional Selection 

In [75]:
array5

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
# condition
array5 > 60 

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [314]:
# array[condition]
array5[array5 > 60]

array([70, 80, 90])

In [77]:
greater60 = array5 > 60
greater60  

array([False, False, False, False, False, False, False,  True,  True,
        True])

In [78]:
array5[greater60] 

array([70, 80, 90])

In [79]:
array5[array5%20 == 0] 

array([ 0, 20, 40, 60, 80])

## 4. Arithmetic

### 1D array

In [81]:
array4 = np.arange(1, 10)
array4 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [84]:
array4 + 100
# angka 100 akan ditambahkan pada tiap item dalam array4

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [87]:
array4 + [100,100,100,100,100,100,100,100,100]

array([101, 102, 103, 104, 105, 106, 107, 108, 109])

In [88]:
array4 + [100,100,100,100,100,100,100,100,100,100]
# error karena array4 punya 9 item, sedangkan listnya berisi 10 item, jadi tidak cocok

ValueError: operands could not be broadcast together with shapes (9,) (10,) 

In [89]:
array4 + [100,200,300,400,500,600,100,100,100] 
# penjumlahan terjadi pada item di index yg sama dari array4 dan list 

array([101, 202, 303, 404, 505, 606, 107, 108, 109])

In [90]:
array4 * array4 

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [91]:
array4 / 10 

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

### 2D array

In [93]:
arr_2d = array4.reshape(3,3)
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr_2d**2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [97]:
arr_1d = np.array([1, 2, 3])
arr_1d

array([1, 2, 3])

In [98]:
arr_2d*arr_1d

array([[ 1,  4,  9],
       [ 4, 10, 18],
       [ 7, 16, 27]])

In [100]:
arr_2d/arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Mathematical Array Function

In [101]:
array4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
# akar
np.sqrt(array4)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        ])

In [105]:
# eksponensial
np.exp(array4)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

In [106]:
# rata-rata
np.mean(array4) 

np.float64(5.0)

In [107]:
np.sin(array4) 

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [108]:
np.log(array4)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

### Other Function

In [109]:
# memasukkan nilai pada index tertentu
array5 = np.insert(array4, 4, 100)
array5 
# np.insert(array, index, value)

array([  1,   2,   3,   4, 100,   5,   6,   7,   8,   9])

In [125]:
array4 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [111]:
# memasukkan nilai pada index terakhir
np.append(array4, 200)

# np.append(array, value)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9, 200])

In [112]:
array4

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
np.delete(array4, 4)

array([1, 2, 3, 4, 6, 7, 8, 9])

### Concatenate

In [115]:
arr1 = np.array([[1,2], [3,4], [5,6]])
arr1 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
arr2 = np.array([[10,20], [30,40]])
arr2 

array([[10, 20],
       [30, 40]])

In [117]:
np.concatenate((arr1, arr2), axis=0)
# axis=0 --> menambah baris atau menempelkan ke bawah

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40]])

In [118]:
np.concatenate((arr1, arr2), axis=1)
# axis=1 --> menambah kolom atau menempelkan ke samping 
# error karena jumlah barisnya berbeda

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [128]:
np.where(array4>5, 1, array4) 

array([1, 2, 3, 4, 5, 1, 1, 1, 1])

In [129]:
np.where(array4>5, 1, 0)

# np.where(condition, True, False)

array([0, 0, 0, 0, 0, 1, 1, 1, 1])