# ``Solution`` - **Python for Data Analysis Exercise**

<hr>

## Import Library

In [1]:
import pandas as pd
import numpy as np

<hr>

## Nomor 1

* Buatlah sebuah array dengan perintah arrange yang nilai start dan end adalah sebuah input!
* Dari array yang terbentuk tersebut, buatlah versi 2 dan 3 dimensinya!


In [2]:
start = int(input('Mulai: '))
end = int(input('Selesai: '))

Mulai:  1
Selesai:  13


In [3]:
data_awal = np.arange(start, end)
data_awal

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [7]:
Dua_Dimensi = data_awal.reshape(3, 4)
Dua_Dimensi

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [10]:
Tiga_Dimensi = data_awal.reshape(2, 3, 2)
Tiga_Dimensi

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

<hr>

## Nomor 2

* Buatlah sebuah array 1 dimensi dari data random integer sebanyak “n”, dimana “n” tersebut adalah sebuah input !
* Batasan random juga ditentukan dalam input.
* Ubahlah array 1 dimensi tersebut ke dalam bentuk 2 dimensi atau matrix!
* Setelah diubah ke bentuk 2 dimensi, setiap barisnya baliklah urutan datanya! Misalnya dari 1, 2, 3 menjadi 3, 2, 1.


In [11]:
# input
n = int(input('Banyak data: '))
start = int(input('Mulai: '))
end = int(input('Selesai: '))

Banyak data:  40
Mulai:  1
Selesai:  21


In [12]:
data = np.random.randint(start, end, n)
data 

array([14,  8, 16,  6,  1, 17,  2, 15, 12, 20,  8,  3, 17, 20, 19, 14, 17,
       16, 19,  9, 15, 16, 16, 11,  2,  6,  5, 19,  1,  2,  9, 17,  2, 19,
        3, 10, 10, 11, 18,  7])

In [13]:
# dua dimensi
duaDim = data.reshape(8, 5)
duaDim

array([[14,  8, 16,  6,  1],
       [17,  2, 15, 12, 20],
       [ 8,  3, 17, 20, 19],
       [14, 17, 16, 19,  9],
       [15, 16, 16, 11,  2],
       [ 6,  5, 19,  1,  2],
       [ 9, 17,  2, 19,  3],
       [10, 10, 11, 18,  7]])

In [14]:
# tukar posisi
duaDim[:, ::-1]

array([[ 1,  6, 16,  8, 14],
       [20, 12, 15,  2, 17],
       [19, 20, 17,  3,  8],
       [ 9, 19, 16, 17, 14],
       [ 2, 11, 16, 16, 15],
       [ 2,  1, 19,  5,  6],
       [ 3, 19,  2, 17,  9],
       [ 7, 18, 11, 10, 10]])

<hr>

## Nomor 3

* Buatlah sebuah array 2 dimensi dengan ukuran 10 x 10
* Isi dari array tersebut adalah : 
1. Sisi luarnya merupakan angka 4
2. Selain sisi luar, angka yang ditampilkan adalah 0


In [17]:
# array 2 dimensi 10 x 10
x = np.ones((10, 10)) * 4
x[1:-1, 1:-1] = 0
x

array([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 0., 0., 0., 0., 0., 0., 0., 0., 4.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.]])

<hr>

## Nomor 4

* Buatlah sebuah Series dengan menggunakan library Pandas!
* Index pada Series tersebut berupa huruf lowercase dari a hingga z.
* Data dari tiap indexnya adalah nomor dari 1 hingga 26.



In [20]:
# buat sebuah series
mylist = list('abcdefghijklmnopqrstuvwxyz')
myarr = np.arange(1, 27)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)
ser

a     1
b     2
c     3
d     4
e     5
f     6
g     7
h     8
i     9
j    10
k    11
l    12
m    13
n    14
o    15
p    16
q    17
r    18
s    19
t    20
u    21
v    22
w    23
x    24
y    25
z    26
dtype: int64

<hr>

## Nomor 5

* Buatlah sebuah Series menggunakan angka random integer dari 1 hingga 5 sebanyak 100!
* Hitunglah banyaknya frekuensi tiap angka!
* Cari tahu 2 nilai dengan frekuensi tertinggi!



In [21]:
# series yang terdiri dari angka random integer 1 sampai 5 sebanyak 100
np.random.seed(101)
num_series = pd.Series(np.random.randint(1, 5, 100))
num_series

0     4
1     4
2     2
3     3
4     4
     ..
95    4
96    1
97    3
98    3
99    3
Length: 100, dtype: int32

In [22]:
# menghitung banyaknya jumlah tiap angka
num_series.value_counts()

4    36
1    30
3    18
2    16
dtype: int64

In [28]:
# mencari tahu 2 angka yang paling sering muncul
df_vc = pd.DataFrame(num_series.value_counts(), columns = ['Frequency']).reset_index()
df_vc = df_vc.rename(columns = {'index': 'value'})
df_vc.sort_values(by='Frequency', ascending=False).head(2)

value  Frequency
0      4         36
1      1         30

<hr>

## Nomor 6

* Import library “seaborn”. Lalu, load data yang bernama “MPG”!
* Tampilkan 5 data teratas pada DataFrame dari data “MPG”!
* Tampilkan statistik deskriptif atau Describe data selain data numerik!
* Tampilkan seluruh nama kolom pada DataFrame!
* Hitung Jumlah Missing Value (data kosong) di setiap kolomnya!

In [29]:
import seaborn as sns
mpg = sns.load_dataset('mpg')
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name  
0          70    usa  chevrolet chevelle malibu  
1          70    usa          buick skylark 320  
2          70    usa         plymouth satellite  
3          70    usa              amc rebel sst  
4          70    usa                ford torino

In [32]:
# describe selain data numerik
mpg.describe(exclude = 'number')

origin        name
count     398         398
unique      3         305
top       usa  ford pinto
freq      249           6

In [33]:
# tampilkan kolom
mpg.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model_year', 'origin', 'name'],
      dtype='object')

In [35]:
# missing values tiap kolom
mpg.isna().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
name            0
dtype: int64

<hr>

## Nomor 7

* Import library “seaborn”, lalu load data yang bernama “MPG”!
* Tampilkan Missing value (data kosong) pada kolom ‘horsepower’!
* Tampilkan index lokasi  missing value tersebut!



In [36]:
mpg[mpg['horsepower'].isna() == True]

mpg  cylinders  displacement  horsepower  weight  acceleration  \
32   25.0          4          98.0         NaN    2046          19.0   
126  21.0          6         200.0         NaN    2875          17.0   
330  40.9          4          85.0         NaN    1835          17.3   
336  23.6          4         140.0         NaN    2905          14.3   
354  34.5          4         100.0         NaN    2320          15.8   
374  23.0          4         151.0         NaN    3035          20.5   

     model_year  origin                  name  
32           71     usa            ford pinto  
126          74     usa         ford maverick  
330          80  europe  renault lecar deluxe  
336          80     usa    ford mustang cobra  
354          81  europe           renault 18i  
374          82     usa        amc concord dl

In [37]:
mpg[mpg['horsepower'].isna() == True].index

Int64Index([32, 126, 330, 336, 354, 374], dtype='int64')

<hr>

## Nomor 8

* Import library “seaborn”, lalu load data yang bernama “MPG”!
* Lakukan grouping atau pengelompokan berdasarkan kolom ‘origin’! Tampilkan rata-rata dari ‘horsepower’ di setiap kelompok origin-nya!

In [39]:
# horse power berdasarkan origin
mpg.groupby('origin').mean()['horsepower']

origin
europe     80.558824
japan      79.835443
usa       119.048980
Name: horsepower, dtype: float64

<hr>

## Nomor 9

* Import library “seaborn”, lalu load data yang bernama “MPG”!
* Buatlah sebuah kolom baru yang bernama ‘horse_origin’! 
* Kolom ‘horse_origin’ ini harus diisi menggunakan fungsi berisikan: 
* Jika nilai ‘horsepower’ <= 105, tampilkan ‘lower’ + ‘nama origin’ pada baris yang sama. Contohnya ‘lower USA’. 
* Jika nilai ‘horsepower’ >= 105, tampilkan ‘upper’ + ‘nama origin’.


In [40]:
# buat function

def add_horse_origin(x):
    if x['horsepower'] <= 105:
        return 'lower {}'.format(x['origin'])
    else:
        return 'upper {}'.format(x['origin'])

In [41]:
# membuat kolom baru menggunakan function
mpg['horse_origin'] = mpg[['horsepower', 'origin']].apply(add_horse_origin, axis = 1)
mpg.head()

mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   

   model_year origin                       name horse_origin  
0          70    usa  chevrolet chevelle malibu    upper usa  
1          70    usa          buick skylark 320    upper usa  
2          70    usa         plymouth satellite    upper usa  
3          70    usa              amc rebel sst    upper usa  
4          70    usa                ford torino    upper usa

<hr>

## Nomor 10
* Import library “seaborn”, lalu load data yang bernama “MPG”!
* Lakukan pengelompokan atau grouping kolom ‘weight’ berdasarkan kolom ‘origin’ dengan aggregating mean, standart deviasi, sum, count, min, dan max!
* Lakukan reset index sehingga kolom ‘origin’ tidak lagi menjadi index tapi tetap menjadi kolom!


In [42]:
# grouping & describe
mpg[['weight', 'origin']].groupby(['origin']).describe()

weight                                                             \
        count         mean         std     min      25%     50%      75%   
origin                                                                     
europe   70.0  2423.300000  490.043191  1825.0  2067.25  2240.0  2769.75   
japan    79.0  2221.227848  320.497248  1613.0  1985.00  2155.0  2412.50   
usa     249.0  3361.931727  794.792506  1800.0  2720.00  3365.0  4054.00   

                
           max  
origin          
europe  3820.0  
japan   2930.0  
usa     5140.0

In [43]:
mpg_agg = mpg[['weight', 'origin']].groupby(['origin']).agg(mean = pd.NamedAgg(column='weight', aggfunc='mean'),
                                                            std = pd.NamedAgg(column='weight', aggfunc='std'),
                                                            sum = pd.NamedAgg(column='weight', aggfunc='sum'),
                                                            count = pd.NamedAgg(column='weight', aggfunc='count'),
                                                            min = pd.NamedAgg(column='weight', aggfunc='min'),
                                                            max = pd.NamedAgg(column='weight', aggfunc='max'),
                                                           )

mpg_agg

mean         std     sum  count   min   max
origin                                                    
europe  2423.300000  490.043191  169631     70  1825  3820
japan   2221.227848  320.497248  175477     79  1613  2930
usa     3361.931727  794.792506  837121    249  1800  5140

In [44]:
# reset index 
mpg_agg.reset_index()

origin         mean         std     sum  count   min   max
0  europe  2423.300000  490.043191  169631     70  1825  3820
1   japan  2221.227848  320.497248  175477     79  1613  2930
2     usa  3361.931727  794.792506  837121    249  1800  5140

<hr>

# **``Thank you``**